import metadata from "@/data/public-budget/metadata.json";
import organizations from "@/data/public-budget/organizations.json";
import monthly from "@/data/public-budget/budget-monthly.json";
import kpi from "@/data/public-budget/kpi-usage.json";
import { buildManagementTrendContract } from "@/lib/budget-monthly-trend-contract";
import { filterBudgetData } from "./filter-budget-data";
import { safeRate } from "./status-policy";
import type { PublicBudgetDataset, ScopeKey, UsageRow } from "./types";
import type { BudgetViewMode } from "@/lib/budget-period-contract";
export const publicBudgetDataset: PublicBudgetDataset = { months: metadata.months, organizations, monthly: monthly as PublicBudgetDataset["monthly"], kpiScenes: kpi.scenes as PublicBudgetDataset["kpiScenes"] };
const scopeLabels: Record<ScopeKey, string> = { workforce_planning: "Workforce Planning", business_operations: "Business Operations" };
function sumNullable(values: Array<number | null>) { return values.some((value) => value === null) ? null : values.reduce<number>((total, value) => total + (value ?? 0), 0); }
function sumActual(values: Array<number | null>) { const available = values.filter((value): value is number => value !== null); return available.length ? available.reduce((total, value) => total + value, 0) : null; }
export function buildBudgetPageModel(reportMonth: string, viewMode: BudgetViewMode, organizationPath: string[]) { const rows = filterBudgetData(publicBudgetDataset.monthly, publicBudgetDataset.organizations, reportMonth, viewMode, organizationPath); const usageRows: UsageRow[] = (["workforce_planning", "business_operations"] as ScopeKey[]).map((scope) => { const scoped = rows.filter((row) => row.scope === scope); const budgetAmount = sumNullable(scoped.map((row) => row.budgetAmount)); const actualAmount = sumActual(scoped.map((row) => row.actualAmount)); const budgetHc = viewMode === "monthly" ? sumNullable(scoped.map((row) => row.budgetHc)) : sumNullable(scoped.filter((row) => row.month === reportMonth).map((row) => row.budgetHc)); const actualHc = viewMode === "monthly" ? sumActual(scoped.map((row) => row.actualHc)) : sumActual(scoped.filter((row) => row.month === reportMonth).map((row) => row.actualHc)); const perCapitaBudget = budgetAmount !== null && budgetHc ? budgetAmount / budgetHc : null; const perCapitaActual = actualAmount !== null && actualHc ? actualAmount / actualHc : null; return { key: scope, label: scopeLabels[scope], budgetAmount, actualAmount, amountRate: safeRate(actualAmount, budgetAmount), budgetHc, actualHc, hcRate: safeRate(actualHc, budgetHc), perCapitaBudget, perCapitaActual, perCapitaRate: safeRate(perCapitaActual, perCapitaBudget) }; }); const totalBudget = sumNullable(usageRows.map((row) => row.budgetAmount)); const totalActual = sumActual(usageRows.map((row) => row.actualAmount)); const trendRows = publicBudgetDataset.months.filter((month) => month <= reportMonth).map((month) => { const source = filterBudgetData(publicBudgetDataset.monthly, publicBudgetDataset.organizations, month, "monthly", organizationPath); const metric = (scope: ScopeKey) => { const selected = source.filter((row) => row.scope === scope); return { budgetAmount: sumNullable(selected.map((row) => row.budgetAmount)), actualAmount: sumActual(selected.map((row) => row.actualAmount)), budgetHc: sumNullable(selected.map((row) => row.budgetHc)), actualHc: sumActual(selected.map((row) => row.actualHc)) }; }; const first = metric("workforce_planning"); const second = metric("business_operations"); return { month, dataStatus: "complete" as const, groupManagement: first, departmentManagement: second, total: { budgetAmount: sumNullable([first.budgetAmount, second.budgetAmount]), actualAmount: sumActual([first.actualAmount, second.actualAmount]), budgetHc: sumNullable([first.budgetHc, second.budgetHc]), actualHc: sumActual([first.actualHc, second.actualHc]) } }; }); return { usageRows, totalBudget, totalActual, totalRate: safeRate(totalActual, totalBudget), trend: buildManagementTrendContract(trendRows), kpiScenes: publicBudgetDataset.kpiScenes }; }
