"use client";
import { DownOutlined, UpOutlined } from "@ant-design/icons";
import { Button, Card, Cascader, Progress, Segmented, Select, Space, Table, Tag, Typography } from "antd";
import { useMemo, useState } from "react";
import BudgetComparisonBarChart from "@/components/charts/BudgetComparisonBarChart";
import BudgetManagementTrendChart from "@/components/charts/BudgetManagementTrendChart";
import PublicKpiCostUsageSection from "@/components/budget/PublicKpiCostUsageSection";
import { budgetPageCssVariables, budgetUiColors } from "@/lib/budget-ui-tokens";
import { getBudgetUsageDisplayCopy } from "@/lib/budget-usage-management";
import type { BudgetViewMode } from "@/lib/budget-period-contract";
import { buildBudgetPageModel, publicBudgetDataset } from "@/lib/public-budget/adapter";
import { statusText, usageStatus } from "@/lib/public-budget/status-policy";
import type { UsageRow } from "@/lib/public-budget/types";
import { budgetDisplayLabel } from "@/components/budget/public-budget-labels";
const { Text } = Typography;
const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });
const count = new Intl.NumberFormat("zh-CN", { maximumFractionDigits: 0 });
function formatMoney(value: number | null) { return value === null ? "--" : money.format(value); }
function formatCount(value: number | null) { return value === null ? "--" : count.format(value); }
function rateText(actual: number | null, budget: number | null) { if (budget === null) return "无预算"; if (budget === 0 || actual === null) return "无法计算"; return `${(actual / budget * 100).toFixed(1)}%`; }
function statusClass(actual: number | null, budget: number | null) { return `status-${usageStatus(actual, budget)}`; }
function ProgressRingCard({ title, actual, budget, actualLabel = "实际", budgetLabel = "预算" }: { title: string; actual: number | null; budget: number | null; actualLabel?: string; budgetLabel?: string }) { const state = usageStatus(actual, budget); const percentage = budget && actual !== null ? Math.min(actual / budget * 100, 100) : 0; const stroke = state === "over" ? budgetUiColors.danger : state === "near" ? budgetUiColors.warning : budgetUiColors.primary; return <Card title={title} size="small" className="budget-metric-card"><div className="budget-metric-content budget-metric-content--ring"><Progress type="circle" size={112} percent={percentage} strokeColor={stroke} trailColor={budgetUiColors.budget} format={() => <span className={`budget-ring-value ${statusClass(actual,budget)}`}>{rateText(actual,budget)}</span>} /><div className="budget-metric-comparison"><div className="budget-metric-breakdown"><span>{actualLabel}</span><strong>{formatMoney(actual)}</strong></div><div className="budget-metric-breakdown"><span>{budgetLabel}</span><strong>{budget === null ? "无预算" : formatMoney(budget)}</strong></div></div><Tag className={`budget-status-tag ${statusClass(actual,budget)}`}>{statusText(actual,budget)}</Tag></div></Card>; }
function SummaryCard({ title, primary, label, rows }: { title: string; primary: string; label: string; rows: Array<[string,string]> }) { return <Card title={title} size="small" className="budget-metric-card budget-target-card"><div className="budget-metric-content"><div className="budget-metric-value">{primary}</div><div className="budget-metric-caption">{label}</div><div className="budget-metric-comparison">{rows.map(([name,value]) => <div className="budget-metric-breakdown" key={name}><span>{name}</span><strong>{value}</strong></div>)}</div></div></Card>; }
function metricColumns(metric: "amount" | "hc" | "avg", copy: ReturnType<typeof getBudgetUsageDisplayCopy>) { const budgetTitle = metric === "amount" ? `${copy.amountPeriodLabel}人力成本预算` : metric === "hc" ? `${copy.headcountPeriodLabel}预算 HC` : `${copy.amountPeriodLabel}人均预算`; const actualTitle = metric === "amount" ? `${copy.amountPeriodLabel}人力成本实际` : metric === "hc" ? `${copy.headcountPeriodLabel}实际 HC` : `${copy.amountPeriodLabel}人均实际`; return [ { title: "类型", dataIndex: "label", key: "label", render: (label: string) => budgetDisplayLabel(label) }, { title: budgetTitle, key: "budget", align: "right" as const, render: (_: unknown, row: UsageRow) => metric === "amount" ? (row.budgetAmount === null ? "无预算" : formatMoney(row.budgetAmount)) : metric === "hc" ? (row.budgetHc === null ? "无预算" : formatCount(row.budgetHc)) : (row.perCapitaBudget === null ? "无法计算" : formatMoney(row.perCapitaBudget)) }, { title: actualTitle, key: "actual", align: "right" as const, render: (_: unknown, row: UsageRow) => <span className={metric === "amount" ? statusClass(row.actualAmount,row.budgetAmount) : metric === "hc" ? statusClass(row.actualHc,row.budgetHc) : statusClass(row.perCapitaActual,row.perCapitaBudget)}>{metric === "amount" ? formatMoney(row.actualAmount) : metric === "hc" ? formatCount(row.actualHc) : formatMoney(row.perCapitaActual)}</span> }, { title: "使用率", key: "rate", align: "right" as const, render: (_: unknown, row: UsageRow) => metric === "amount" ? rateText(row.actualAmount,row.budgetAmount) : metric === "hc" ? rateText(row.actualHc,row.budgetHc) : rateText(row.perCapitaActual,row.perCapitaBudget) } ]; }
export default function BudgetPage() {
  const [currentMonth, setCurrentMonth] = useState("2026-07"); const [viewMode, setViewMode] = useState<BudgetViewMode>("monthly"); const [organizationScope, setOrganizationScope] = useState<string[]>([]); const [budgetDetailsExpanded, setBudgetDetailsExpanded] = useState(false);
  const model = useMemo(() => buildBudgetPageModel(currentMonth, viewMode, organizationScope), [currentMonth, viewMode, organizationScope]);
  const copy = getBudgetUsageDisplayCopy(currentMonth, viewMode); const contextLabel = organizationScope.length ? publicBudgetDataset.organizations.find((item) => item.id === organizationScope.at(-1))?.label ?? "所选组织" : "全部组织";
  const orgOptions = publicBudgetDataset.organizations.filter((item) => item.parentId === null).map((parent) => ({ value: parent.id, label: budgetDisplayLabel(parent.label), children: publicBudgetDataset.organizations.filter((item) => item.parentId === parent.id).map((child) => ({ value: child.id, label: budgetDisplayLabel(child.label) })) }));
  const first = model.usageRows[0]; const second = model.usageRows[1]; const totalHcBudget = model.usageRows.reduce((total,row) => total + (row.budgetHc ?? 0), 0); const totalHcActual = model.usageRows.reduce((total,row) => total + (row.actualHc ?? 0), 0);
  const incentiveBudget = model.kpiScenes.flatMap((scene) => scene.groups).flatMap((group) => group.subjects).reduce((sum,item) => sum + (item.budget ?? 0),0); const incentiveActual = model.kpiScenes.flatMap((scene) => scene.groups).flatMap((group) => group.subjects).reduce((sum,item) => sum + (item.actual ?? 0),0);
  return <div className="budget-page" style={budgetPageCssVariables}>
    <div className="budget-filter-bar"><div><h1 className="budget-page-title">预算进度</h1><div className="budget-page-subtitle">按月份与组织范围查看预算使用、HC 和人均成本趋势</div></div><div className="budget-filter-controls"><Space size={8} className="budget-filter-item"><Text className="budget-filter-label">统计月份：</Text><Select value={currentMonth} options={publicBudgetDataset.months.map((value) => ({value,label:value}))} style={{width:150}} onChange={setCurrentMonth}/></Space><Space size={8} className="budget-filter-item"><Text className="budget-filter-label">数据范围：</Text><Segmented value={viewMode} options={[{label:"当月",value:"monthly"},{label:"累计（年初至当月）",value:"ytd"}]} onChange={(value) => setViewMode(value as BudgetViewMode)}/></Space><Space size={8} className="budget-filter-item"><Text className="budget-filter-label">组织架构：</Text><Cascader value={organizationScope} options={orgOptions} changeOnSelect allowClear placeholder="全部组织" style={{minWidth:230}} onChange={(value) => setOrganizationScope((value as string[]) ?? [])}/></Space></div></div>
    <div className="budget-top-grid"><ProgressRingCard title={viewMode === "monthly" ? `${Number(currentMonth.slice(5))}月人力成本使用率` : "累计人力成本使用率"} actual={model.totalActual} budget={model.totalBudget}/><ProgressRingCard title="职能管理岗使用率" actual={first.actualAmount} budget={first.budgetAmount}/><ProgressRingCard title="业务管理岗使用率" actual={second.actualAmount} budget={second.budgetAmount}/><SummaryCard title={viewMode === "monthly" ? `${Number(currentMonth.slice(5))}月成本管控` : "累计成本管控"} primary={rateText(model.totalActual,model.totalBudget)} label={statusText(model.totalActual,model.totalBudget)} rows={[["实际人力成本",formatMoney(model.totalActual)],["人力成本预算",model.totalBudget === null ? "无预算" : formatMoney(model.totalBudget)],["实际 HC",formatCount(totalHcActual)],["预算 HC",formatCount(totalHcBudget)]]}/><ProgressRingCard title="激励费用使用进度" actual={incentiveActual} budget={incentiveBudget}/></div>
    <Card title="预算使用" size="small" className="budget-section-card"><div className="budget-section-context">当前范围：{budgetDisplayLabel(contextLabel)} · {copy.monthLabel} · {copy.viewModeLabel}</div><div className="budget-three-grid"><Card title={copy.laborCostTitle} size="small" className="budget-chart-card"><BudgetComparisonBarChart rows={model.usageRows} metric="amount" budgetName={`${copy.amountPeriodLabel}人力成本预算`} actualName={`${copy.amountPeriodLabel}人力成本实际`}/></Card><Card title={copy.headcountTitle} size="small" className="budget-chart-card"><BudgetComparisonBarChart rows={model.usageRows} metric="hc" budgetName={`${copy.headcountPeriodLabel}预算 HC`} actualName={`${copy.headcountPeriodLabel}实际 HC`}/></Card><Card title={copy.averageCostTitle} size="small" className="budget-chart-card"><BudgetComparisonBarChart rows={model.usageRows} metric="perCapita" budgetName={`${copy.amountPeriodLabel}人均预算`} actualName={`${copy.amountPeriodLabel}人均实际`}/></Card></div><div className="budget-detail-toggle-row"><Button type="text" size="small" className="budget-detail-toggle" icon={budgetDetailsExpanded ? <UpOutlined/> : <DownOutlined/>} onClick={() => setBudgetDetailsExpanded(!budgetDetailsExpanded)}>{budgetDetailsExpanded ? "收起明细表格" : "展开明细表格"}</Button></div>{budgetDetailsExpanded ? <div className="budget-three-grid budget-detail-tables"><Card size="small" className="budget-table-card"><Table rowKey="key" pagination={false} size="small" dataSource={model.usageRows} columns={metricColumns("amount",copy)} scroll={{x:580}}/></Card><Card size="small" className="budget-table-card"><Table rowKey="key" pagination={false} size="small" dataSource={model.usageRows} columns={metricColumns("hc",copy)} scroll={{x:520}}/></Card><Card size="small" className="budget-table-card"><Table rowKey="key" pagination={false} size="small" dataSource={model.usageRows} columns={metricColumns("avg",copy)} scroll={{x:560}}/></Card></div> : null}</Card>
    <Card size="small" className="budget-section-card budget-local-analysis"><div className="budget-two-grid"><Card title="人力成本预算消耗趋势" size="small" className="budget-chart-card"><BudgetManagementTrendChart data={model.trend} metric="amount" height={340}/></Card><Card title="人均预算趋势" size="small" className="budget-chart-card"><BudgetManagementTrendChart data={model.trend} metric="perCapita" height={340}/></Card></div></Card>
    <PublicKpiCostUsageSection scenes={model.kpiScenes}/><div className="synthetic-note">模拟数据 · 页面仅使用公开版预算数据，不连接企业接口、身份系统或数据库。</div>
  </div>;
}
