import type { CSSProperties } from "react";

export const budgetUiColors = {
  pageBackground: "#F5F7FA",
  cardBackground: "#FFFFFF",
  sectionBackground: "#F8FAFC",
  primary: "#4F6FAF",
  primaryHover: "#425F98",
  primarySoft: "#EEF3FA",
  secondaryBlue: "#7895C7",
  budget: "#D9E1EC",
  textPrimary: "#1F2937",
  textSecondary: "#526071",
  textTertiary: "#7B8798",
  border: "#E3E8EF",
  borderSubtle: "#EDF1F5",
  tableHeader: "#F6F8FB",
  tableHover: "#F4F7FB",
  neutralSoft: "#F1F4F8",
  disabledBackground: "#F2F4F7",
  disabledText: "#98A2B3",
  warning: "#6B6FA8",
  warningSoft: "#F2F3FA",
  warningBorder: "#D5D7EA",
  danger: "#C86666",
  dangerSoft: "#FFF2F2",
  dangerBorder: "#E7BABA",
  success: "#4F7D68",
  successSoft: "#F1F7F4",
  successBorder: "#C9DDD2",
  tooltip: "#253247",
  businessDirect: "#4F6FAF",
  businessHome: "#6F7F8E",
} as const;

export const budgetPageCssVariables = {
  "--budget-page-bg": budgetUiColors.pageBackground,
  "--budget-card-bg": budgetUiColors.cardBackground,
  "--budget-section-bg": budgetUiColors.sectionBackground,
  "--budget-primary": budgetUiColors.primary,
  "--budget-primary-hover": budgetUiColors.primaryHover,
  "--budget-primary-soft": budgetUiColors.primarySoft,
  "--budget-secondary-blue": budgetUiColors.secondaryBlue,
  "--budget-baseline": budgetUiColors.budget,
  "--budget-text-primary": budgetUiColors.textPrimary,
  "--budget-text-secondary": budgetUiColors.textSecondary,
  "--budget-text-tertiary": budgetUiColors.textTertiary,
  "--budget-border": budgetUiColors.border,
  "--budget-border-subtle": budgetUiColors.borderSubtle,
  "--budget-table-header": budgetUiColors.tableHeader,
  "--budget-table-hover": budgetUiColors.tableHover,
  "--budget-neutral-soft": budgetUiColors.neutralSoft,
  "--budget-disabled-bg": budgetUiColors.disabledBackground,
  "--budget-disabled-text": budgetUiColors.disabledText,
  "--budget-warning": budgetUiColors.warning,
  "--budget-warning-soft": budgetUiColors.warningSoft,
  "--budget-warning-border": budgetUiColors.warningBorder,
  "--budget-danger": budgetUiColors.danger,
  "--budget-danger-soft": budgetUiColors.dangerSoft,
  "--budget-danger-border": budgetUiColors.dangerBorder,
  "--budget-success": budgetUiColors.success,
  "--budget-success-soft": budgetUiColors.successSoft,
  "--budget-success-border": budgetUiColors.successBorder,
  "--budget-radius-card": "8px",
  "--budget-radius-control": "6px",
  "--budget-control-height": "34px",
  "--budget-section-gap": "20px",
} as CSSProperties;
