"use client";
import { DownOutlined, UpOutlined } from "@ant-design/icons";
import { Card } from "antd";
import { useState } from "react";
import { statusText, usageStatus } from "@/lib/public-budget/status-policy";
import type { KpiScene, KpiSubject } from "@/lib/public-budget/types";
import { budgetDisplayLabel } from "@/components/budget/public-budget-labels";
const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });
function ratio(actual: number | null, budget: number | null) { return budget && actual !== null ? `${(actual / budget * 100).toFixed(1)}%` : budget === null ? "无预算" : "无法计算"; }
function Subject({ subject, stateKey }: { subject: KpiSubject; stateKey: string }) { const [open, setOpen] = useState(false); const status = usageStatus(subject.actual, subject.budget); return <div className="budget-kpi-subject"><button className="budget-kpi-subject-button" onClick={() => setOpen(!open)} aria-expanded={open}><strong>{budgetDisplayLabel(subject.label)}</strong><span className="budget-kpi-muted">{budgetDisplayLabel(subject.metricLabel)}</span><span>预算：<b>{subject.budget === null ? "无预算" : money.format(subject.budget)}</b></span><span>实际：<b>{subject.actual === null ? "--" : money.format(subject.actual)}</b></span><span className={`budget-rate status-${status}`}>{ratio(subject.actual, subject.budget)}</span><span className={`budget-kpi-status status-${status}`}>{statusText(subject.actual, subject.budget)}</span><span>{open ? <UpOutlined /> : <DownOutlined />}</span></button>{open ? <div className="budget-kpi-subject-detail"><div className="budget-kpi-detail-shell"><table className="budget-kpi-detail-table"><thead><tr><th>明细</th><th>预算</th><th>实际</th><th>实际/预算</th><th>状态</th></tr></thead><tbody>{subject.details.map((detail) => <tr key={`${stateKey}-${detail.key}`}><td>{budgetDisplayLabel(detail.label)}</td><td>{detail.budget === null ? "无预算" : money.format(detail.budget)}</td><td>{detail.actual === null ? "--" : money.format(detail.actual)}</td><td>{ratio(detail.actual, detail.budget)}</td><td>{statusText(detail.actual, detail.budget)}</td></tr>)}</tbody></table></div></div> : null}</div>; }
export default function PublicKpiCostUsageSection({ scenes }: { scenes: KpiScene[] }) { const [openGroups, setOpenGroups] = useState<string[]>([]); return <Card title={<div><div className="budget-kpi-module-title">KPI / 激励费用使用情况</div><div className="budget-kpi-module-description">按场景 → 分组 → 科目 → 明细展开预算与实际</div></div>} size="small" className="budget-kpi-card"><div className="budget-kpi-scenes">{scenes.map((scene) => <section key={scene.key} className="budget-kpi-scene"><header className="budget-kpi-scene-header"><i /> <div><strong>{budgetDisplayLabel(scene.label)}</strong><span>场景</span></div></header><div className="budget-kpi-scene-body">{scene.groups.map((group) => { const key = `${scene.key}-${group.key}`; const open = openGroups.includes(key); return <div key={key} className="budget-kpi-group"><button className="budget-kpi-group-button" onClick={() => setOpenGroups((current) => open ? current.filter((item) => item !== key) : [...current, key])}><span><strong>{budgetDisplayLabel(group.label)}</strong><small>分组 · {group.subjects.length} 项科目</small></span>{open ? <UpOutlined /> : <DownOutlined />}</button>{open ? <div className="budget-kpi-group-expanded">{group.subjects.map((subject) => <Subject key={subject.key} subject={subject} stateKey={key} />)}</div> : null}</div>; })}</div></section>)}</div></Card>; }
